# Generated by Django 2.2 on 2019-09-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_movie_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
    ]
